### ISSUE TITLE
Incompatible with migration_comments

### ISSUE THREAD

**Issue by allenwq** [SchemaPlus/schema_monkey#13]
We use https://github.com/pinnymz/migration_comments together with schama_plus, but there are certain issues.

After 2.1.2:
    `$ rake db:migrate`:
```
NoMethodError: private method `print' called for nil:NilClass
Did you mean?  printf
               sprintf
/.rvm/gems/ruby-2.3.0@4.2/gems/migration_comments-0.4.1/lib/migration_comments/active_record/schema_dumper.rb:12:in `table'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/schema_dumper.rb:97:in `block in tables'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/schema_dumper.rb:96:in `each'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/schema_dumper.rb:96:in `tables'
/.rvm/gems/ruby-2.3.0@4.2/gems/schema_plus_core-1.0.1/lib/schema_plus/core/active_record/schema_dumper.rb:43:in `block in tables'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:54:in `call_implementation'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:84:in `_modware_continue'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:76:in `_modware_call'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:82:in `_modware_continue'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:76:in `_modware_call'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:82:in `_modware_continue'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:76:in `_modware_call'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:43:in `execute'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:19:in `start'
/.rvm/gems/ruby-2.3.0@4.2/gems/schema_monkey-2.1.2/lib/schema_monkey/stack.rb:34:in `start'
/.rvm/gems/ruby-2.3.0@4.2/gems/schema_plus_core-1.0.1/lib/schema_plus/core/active_record/schema_dumper.rb:42:in `tables'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/schema_dumper.rb:38:in `dump'
/.rvm/gems/ruby-2.3.0@4.2/gems/schema_plus_core-1.0.1/lib/schema_plus/core/active_record/schema_dumper.rb:17:in `dump'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/schema_dumper.rb:22:in `dump'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:240:in `block (4 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:239:in `open'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:239:in `block (3 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:52:in `block (2 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/bin/ruby_executable_hooks:15:in `eval'
/.rvm/gems/ruby-2.3.0@4.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:dump
```

after 2.1.5:
    `$ rake db:migrate`:
```
NameError: undefined local variable or method `its' for #<Modware::Stack::Middleware:0x007fd503d6e928>
/.rvm/gems/ruby-2.3.0@4.2/gems/schema_plus_enums-0.1.3/lib/schema_plus/enums/middleware.rb:10:in `after'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:46:in `block in execute'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:45:in `each'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:45:in `execute'
/.rvm/gems/ruby-2.3.0@4.2/gems/modware-0.1.3/lib/modware/stack.rb:19:in `start'
/.rvm/gems/ruby-2.3.0@4.2/gems/schema_monkey-2.1.5/lib/schema_monkey/stack.rb:34:in `start'
/.rvm/gems/ruby-2.3.0@4.2/gems/schema_plus_core-1.0.1/lib/schema_plus/core/active_record/schema_dumper.rb:34:in `extensions'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/schema_dumper.rb:37:in `dump'
/.rvm/gems/ruby-2.3.0@4.2/gems/schema_plus_core-1.0.1/lib/schema_plus/core/active_record/schema_dumper.rb:17:in `dump'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/schema_dumper.rb:22:in `dump'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:240:in `block (4 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:239:in `open'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:239:in `block (3 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:52:in `block (2 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/gems/activerecord-4.2.6/lib/active_record/railties/databases.rake:45:in `block (2 levels) in <top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/.rvm/gems/ruby-2.3.0@4.2/bin/ruby_executable_hooks:15:in `eval'
/.rvm/gems/ruby-2.3.0@4.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:dump
```

**Comment by ronen** [comment]
```
NameError: undefined local variable or method `its' for #<Modware::Stack::Middleware:0x007fd503d6e928>
/.rvm/gems/ruby-2.3.0@4.2/gems/schema_plus_enums-0.1.3/lib/schema_plus/enums/middleware.rb:10:in `after'
```
Fixed in schema_plus_enums version 0.1.4

```
NoMethodError: private method `print' called for nil:NilClass
Did you mean?  printf
               sprintf
/.rvm/gems/ruby-2.3.0@4.2/gems/migration_comments-0.4.1/lib/migration_comments/active_record/schema_dumper.rb:12:in `table'
```

I took a quick look at the source of migration_comments, this seems like a load order issue. I think it should work if migration_comments is required first, then schema_plus (specifically schema_plus_core).  Bundler apparently respects the order gems are listed in a Gemfile (see http://stackoverflow.com/a/16725346/1056941) so make sure your Gemfile looks like

```
gem 'migration_comments'
[...]
gem 'schema_plus'
```

rather than 

```
gem 'schema_plus'
[...]
gem 'migration_comments'
```

It's possible I may have befuddled myself thinking about this and the order should be opposite, so if one way doesn't work, try the other :) 
 
Let me know if this helps.

**Comment by allenwq** [comment]
@ronen Thanks for the detailed suggestions ! Will do a test and get back to you :-P

**Comment by allenwq** [comment]
@ronen Thanks again. it's fixed.
